// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DarkModeController from "./dark_mode_controller"
application.register("dark-mode", DarkModeController)

import DatepickerController from "./datepicker_controller"
application.register("datepicker", DatepickerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import MapSingleController from "./map_single_controller"
application.register("map-single", MapSingleController)

import SweetalertController from "./sweetalert_controller"
application.register("sweetalert", SweetalertController)

import ThreeController from "./three_controller"
application.register("three", ThreeController)
